Repository convos-chat/convos, pull requests merged in 2020-07, with the labels that each got.

#506 Fix exif rotation
  assets/js/EmbedMaker.js
Labels: bug

#505 Add users editor
  assets/components/OperationStatus.svelte
  assets/components/SidebarChat.svelte
  assets/js/Time.js
  assets/page/SettingsAdmin.svelte
  assets/page/SettingsAdminUsers.svelte
  assets/routes.js
  assets/sass/components/_form.scss
  lib/Convos/Controller/User.pm
  lib/Convos/Core.pm
  lib/Convos/Core/Settings.pm
  lib/Convos/Util.pm
  public/convos-api.yaml
  t/web-user.t
  t/web-users.t
Labels: enhancement

#510 Update javascript dependencies
  package.json
  pnpm-lock.yaml
  rollup.config.js
Labels: bug, enhancement
