Repository convos-chat/convos, pull requests merged in 2020-11, with the labels that each got.

#522 Ensure markdown link text start with a letter
  __tests__/md.js
  assets/js/md.js
Labels: bug

#523 Fix jumping to bottom of conversation on initial render
  assets/components/InfinityScroll.svelte
Labels: bug

#524 Chat input is coupled to conversation and restored when we go back from settings
  assets/components/ChatInput.svelte
  assets/store/Conversation.js
Labels: enhancement

#526 Tweak _write_and_wait_p example for clarity
  lib/Convos/Core/Connection/Irc.pm
Labels: documentation

#528 Show more info from WHOIS response by default
  assets/store/Connection.js
Labels: enhancement

#529 Add "realname" as a new connection parameter
  assets/components/ConnectionForm.svelte
  assets/js/ConnectionURL.js
  lib/Convos/Core/Connection/Irc.pm
  t/Server/Irc.pm
  t/irc-connect-realname.t
  t/irc-connect.t
Labels: enhancement

#530 Clicking on a nick will create a new conversation
  assets/components/ChatParticipants.svelte
  assets/components/Link.svelte
  assets/js/renderMessages.js
  assets/page/Chat.svelte
  assets/store/Connection.js
  assets/store/Conversation.js
Labels: enhancement

#531 Don't send a username with a non-alphanumeric first character
  lib/Convos/Core/Connection/Irc.pm
  t/irc-connect-realname.t
Labels: bug

#527 New setting to ignore statuses (john joined/john parted)
  assets/page/SettingsAccount.svelte
  assets/store/Connection.js
  assets/store/Conversation.js
  assets/store/User.js
Labels: enhancement

#532 Service account messages will go into the connection dialog #379
  assets/store/Connection.js
  lib/Convos/Core/Connection.pm
  lib/Convos/Core/Connection/Irc.pm
  t/irc-basic.t
  t/irc-events.t
  t/irc-message.t
  t/web-connections.t
  t/web-conversation.t
  t/web-user.t
Labels: enhancement, ux

#534 Adds open mouth, red hear and kissing emojis
  assets/js/md.js
Labels: enhancement

#538 Allow leading uppercase characters in usernames
  lib/Convos/Core/Connection/Irc.pm
  t/irc-connect-realname.t
Labels: bug

#535 Add a "compact display" mode as Viewport option
  assets/page/SettingsAccount.svelte
  assets/sass/components/_chat-messages.scss
  assets/store/Viewport.js
  templates/layouts/convos.html.ep
Labels: enhancement
