Repository convos-chat/convos, pull requests merged in 2021-01, with the labels that each got.

#545 Added Spanish translation
  assets/i18n/es.po
Labels: enhancement, ux

#548 Added Italian translation
  assets/i18n/it.po
Labels: enhancement, ux

#549 Translate convos to Norwegian.
  assets/i18n/no.po
Labels: enhancement, ux

#556 Fix typo
  doc/faq.md
Labels: bug, documentation

#553 Translate new strings to Nårsk
  assets/i18n/no.po
Labels: documentation, help wanted, ux

#552 Spanish translation updated
  assets/i18n/es.po
Labels: documentation, help wanted, ux

#560 Moved search logic from frontend to backend and changed keywords
  assets/i18n/en.po
  assets/i18n/it.po
  assets/i18n/no.po
  assets/page/Search.svelte
  assets/store/Search.js
  lib/Convos/Controller/Search.pm
  lib/Convos/Core/Backend/File.pm
  t/web-search.t
Labels: enhancement
